repos:
-   repo: local
    rev: ''  # pick a git hash / tag to point to
    hooks:
      -   id: flake8

-   repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort